### ISSUE TITLE
CSS builds incorrectly

### ISSUE THREAD

**Issue by silvenon** [assetgraph/assetgraph-builder#151]
I'm authoring my styles in Sass, then compiling to CSS before handing it over to assetgraph-builder. Then during the build I get a warning:

```
No input files specified, defaulting to file:///Users/matija/myproject/.tmp/*.html
 ✔ 0.001 secs: logEvents
 ✔ 0.001 secs: registerRequireJsConfig
 ✔ 0.004 secs: registerLabelsAsCustomProtocols
 ✔ 0.438 secs: loadAssets
 ✔ 0.705 secs: populate
 ✔ 0.437 secs: assumeRequireJsConfigHasBeenFound
 ⚠ WARN: .tmp/styles/main.css: Parse error in .tmp/styles/main.css(line 6107, column 48):
         Unexpected } (line 6107, char 48)
         Falling back to using the 1460 parsed CSS rules
 ✔ 1.939 secs: populate
 ✔ 0.003 secs: fixBaseAssetsOfUnresolvedOutgoingRelationsFromHtmlFragments
 ✔ 0.000 secs: assumeThatAllHtmlFragmentAssetsWithoutIncomingRelationsAreNotTemplates
 ✔ 0.062 secs: populate
 ✔ 0.002 secs: removeRelations
 ✔ 0.023 secs: addDataVersionAttributeToHtmlElement
 ✔ 0.001 secs: replaceDartWithJavaScript
 ✔ 0.000 secs: populate
 ✔ 0.000 secs: compileLessToCss
 ✔ 0.002 secs: removeRelations
 ✔ 0.001 secs: compileScssToCss
 ✔ 0.236 secs: populate
 ✔ 0.237 secs: compileJsxToJs
```

I let it run all the way, then when I look at the site a lot of CSS seems to be missing or broken, basically only the half of my home page renders correctly. I checked if cssmin screwed it up, but it didn't.

Could you help me debug this? I don't know at which step this warning occurred.

**Comment by Munter** [comment]
We're talking about switching from CSSOM to Postcss in https://github.com/assetgraph/assetgraph/issues/195

This might fix this issue

**Comment by papandreou** [comment]
The switch to postcss happened a while ago. Please reopen if this still happens.
