### ISSUE TITLE
Option for disabling MD5 prefix

### ISSUE THREAD

**Issue by silvenon** [assetgraph/assetgraph-builder#159]
In some cases I need assets not to have the cache-busting prefix.

**Comment by Munter** [comment]
It would be quite easy adding a `--no-rev` option. That would have zero granularity though. Would that be enough to cover your use cases you do you need more lowlevel control?

**Comment by silvenon** [comment]
That’s enough :smiley: I never needed more lowlevel control.

**Comment by Munter** [comment]
Available in assetgraph-builder@2.11.0 using the `--nofilerev` command line option for `buildProduction`

**Comment by Munter** [comment]
Also in grunt-reduce@1.4.0 and generator-greenfield@1.6.0

**Comment by silvenon** [comment]
:metal:
