### ISSUE TITLE
buildProduction does not map GETSTATICURL when html tags are omitted

### ISSUE THREAD

**Issue by rolandliwag** [assetgraph/assetgraph-builder#161]
I have an Htmlizer template file with no <html> tags and GETSTATICURL() used in some way. After applying buildProduction, the output file has no GETSTATICURL as expected but the path to the asset is not transformed to its new path. 

eg:
index.html:
    `<div data-bind="html: GETSTATICURL('data.json')"></div>`

data.json:
    `{}`

After buildProduction (expected):
    `<div data-bind="html:'static/data.99914b932b.json'"></div>`

After buildProduction (actual):
    index.html:
    `<div data-bind="html:'data.json'"></div>`

**Comment by papandreou** [comment]
This looks very familiar. I think we managed to fix it in https://github.com/assetgraph/assetgraph/commit/d73ee58d6f948316a1077fb3a8d82dd8a224e14c provided that you use a root-relative url to `data.json`. That commit is not in a release yet, but ping me about it tomorrow, then I'll take a look :)
