### ISSUE TITLE
Segmentation fault on --gzip

### ISSUE THREAD

**Issue by silvenon** [assetgraph/assetgraph-builder#163]
When I add `--gzip` I get:

```
Segmentation fault: 11
```

The error occurs with a HTML file containing nothing but a single referenced JS file.

**Comment by silvenon** [comment]
Tests also fail for me:

```
sh: line 1: 95352 Segmentation fault: 11  mocha
```

You probably won't be able to reproduce the error, because tests pass on Travis. I guess this is more of a bookmark for me.

**Comment by Munter** [comment]
Is this on node 0.12 as well?

**Comment by silvenon** [comment]
No, 0.10.36.

**Comment by papandreou** [comment]
We are currently running node-zopfli@1.2.1, which is the newest version. Node 0.11 compatibility landed [long ago](https://github.com/pierreinglebert/node-zopfli/issues/4). I hope the error can somehow be explained by a non-binary compatible `node_modules` folder you have lying around somewhere.

**Comment by silvenon** [comment]
Right before I raised this issue I cloned this repo and installed deps from scratch. But I'll close this as I'm 99.99% certain it's my fault again.
