### ISSUE TITLE
UTF-8 characters as object keys

### ISSUE THREAD

**Issue by rolandliwag** [assetgraph/assetgraph-builder#164]
This bit of html breaks in IE11 because buildProduction strips the quotes around the object properties.

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <script>

    var i={"ဇ":"z","စျ":"za","ည":"ny"};

    </script>
</head>
<body></body>
</html>
```

IE does not like this for some reason. This is a small snippet of code taken from speakingurl.

**Comment by Munter** [comment]
Thanks for the feedback. We're aware of the problem. It's tracked here: https://github.com/assetgraph/assetgraph/issues/111

It's a problem with uglifyjs, and thus a bit out of our hands. The issue still seems to be unresolved https://github.com/mishoo/UglifyJS2/issues/54

**Comment by papandreou** [comment]
Does `buildProduction --asciionly` work?

**Comment by rolandliwag** [comment]
@papandreou IE still complains about it. It turns it into:

```
var i={\u1007:"z",\u1005\u103b:"za",\u100a:"ny"};
```

**Comment by papandreou** [comment]
Then I'm afraid the only option is patching uglify-js. The good news is that we're already using a fork. See if you can implement a OutputStream (lib/output.js) option that fixes this, then PR it to https://github.com/papandreou/uglifyjs2

**Comment by papandreou** [comment]
Ah, wait. There is also `--quotekeys`, which produces this output:

```js
var i={"ဇ":"z","စျ":"za","ည":"ny"}
```

I just fixed a quirk with how the boolean command line options are parsed and released assetgraph-builder 3.2.0. Either upgrade to that and use `buildProduction --quotekeys`.

(otherwise you will have to use `buildProduction --quotekeys true`, which will break when you upgrade.

**Comment by papandreou** [comment]
And if that does not work either, try `--asciionly --quotekeys`, which gives you:

```js
var i={"\u1007":"z","\u1005\u103b":"za","\u100a":"ny"};
```

**Comment by rolandliwag** [comment]
Hey ```quotekeys``` should be enough and sort of preferred in my opinion since it is exactly how the original source looks (and works in IE). Thanks!

**Comment by Munter** [comment]
Maybe we should make it the default. I'd really like us to automatically fix all of these corner cases developers should never have to think about

**Comment by papandreou** [comment]
I agree. It should be the default in UglifyJs, though. Turning on `--quotekeys` for everything will result in many unnecessary quotes as well.
