### ISSUE TITLE
Autoprefixer v5.x is failing (was "add autoprefixer dependency")

### ISSUE THREAD

**Issue by silvenon** [assetgraph/assetgraph-builder#168]
When using the `browsers` option, the user should have `autoprefixer` installed in their project. The supported version seems to be `^3.1.0`, while the current one is `5.1.0`, which fails on this line:

```js
browsers = autoprefixer.prefixes.browsers;
```

because `browsers` are now located in `autoprefixer.data.browsers` (I haven't actually tested that, though). The solution would maybe be to add `autoprefixer@3.1.0` as a dependency of this package?

**Comment by Munter** [comment]
For all sort of external compilers we want to have the installation optional and let people install the version they need. If we are failing on a specific version of autoprefixer we should add more version specific compatibility layers here: https://github.com/assetgraph/assetgraph-builder/blob/master/lib/loadAndInstantiateAutoprefixer.js#L20-L24

**Comment by silvenon** [comment]
Oh, I see. That makes sense.

**Comment by mwoc** [comment]
Is fixed by https://github.com/assetgraph/assetgraph-builder/pull/160, which hasn't been merged yet.

**Comment by Munter** [comment]
Hmm. Slipped through the cracks. @papandreou #160 looks good to me. Any reason not to merge?

**Comment by papandreou** [comment]
No, I think it's good to go. Just wanted a second pair of eyes on it first.

**Comment by Munter** [comment]
Merged and released in assetgraph-builder v3.3.3

@silvenon does it work now?

**Comment by silvenon** [comment]
Yes, thanks!
