### ISSUE TITLE
Content of data-htmlizer argument gets re-serialized incorrectly

### ISSUE THREAD

**Issue by mwoc** [assetgraph/assetgraph-builder#173]
When using https://github.com/Munawwar/Htmlizer in a page, and its 'data-htmlizer' argument, and using applyBabelJob, the content gets re-serialized incorrectly:

`-<div data-htmlizer="if: foo > 1">`
`+<div data-htmlizer="if: foo &gt; 1">`

I suppose data-htmlizer should be added to a whitelist somewhere to prevent this.  @papandreou ?

**Comment by papandreou** [comment]
Fix released in 3.5.4.

**Comment by mwoc** [comment]
Nice, thanks!
