### ISSUE TITLE
support autoprefixer syntax for >=5

### ISSUE THREAD

**Issue by gustavnikolaj** [assetgraph/assetgraph-builder#174]
autoprefixer changed it's api again in version 5. We will need to support that new way of doing it. 

> Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead

https://github.com/assetgraph/assetgraph-builder/blob/master/lib/transforms/autoprefixer.js#L24

**Comment by Munter** [comment]
Similar to https://github.com/Munter/tolk/blob/master/lib/tolk.js#L117

**Comment by papandreou** [comment]
Fixed a while ago in 8d63a0b0.
