### ISSUE TITLE
When browsers list is not configured, look for it in package.json

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph-builder#534]
A lot of tools are standardising on configuring autoprefixer browserslist in package.json:

```
{
  browserslist: [],
}
```

Maybe we should do the same as a fallback if no command line argument has been supplied

The same might be valuable for express-autoprefixer

**Comment by papandreou** [comment]
I've seen that as well. Great idea!

**Comment by papandreou** [comment]
This landed in 6.1.0.
