### ISSUE TITLE
Support .browserslistrc and browserslist key in package.json

### ISSUE THREAD

**Issue by papandreou** [assetgraph/assetgraph-builder#539]
https://github.com/ai/browserslist#browserslist

**Comment by Munter** [comment]
Looks like getting the info from package.json has already been taken care of: https://github.com/ai/browserslist/blob/master/index.js#L181-L209

**Comment by papandreou** [comment]
Awesome! We should add a few test cases to ag-b, though.

**Comment by salomvary** [comment]
Unfortunately the way `assetgraph-builder` uses `browserslist` does not support reading browser lists from config files like `package.json`. The current implementation either requires passing in  `browsers` argument(s) (eg. `buildProduction --browsers 'last 2 version'`) in which case the browser list will be taken from that argument, or - if the argument is not present - no browser lists will be used at all (even if config files are present). 

Forcing `browserslist` to use config files is pretty easy by [using the zero-argument form of the API call](https://github.com/ai/browserslist#js-api). I would say this should be the default case if no `--browsers` argument is present but that will mean a breaking change to assetgraph-builder (it will suddenly use previously ignored browserslist config).

**Comment by papandreou** [comment]
I chose not to bump the major version, as users will probably think of it as a bug more than anything.
