### ISSUE TITLE
Is it possible to wrap the built JS in a function to not expose define() ?

### ISSUE THREAD

**Issue by rolandliwag** [assetgraph/assetgraph-builder#542]
The requirejs optimizer supports a wrap option that does this. Is this possible with buildProduction?

**Comment by papandreou** [comment]
Which requirejs option is that? I guess it would be easy to expose it.

**Comment by rolandliwag** [comment]
I found it mentioned here: http://requirejs.org/docs/faq-optimization.html
The option is "wrap" and accepts either an object or boolean true.

**Comment by papandreou** [comment]
I [tried it out](https://github.com/assetgraph/assetgraph/commit/2e203ed9f8844bc237c52050c8c6f65fe6a2b681), and it looks like it's already passed through to the require.js optimizer if it's in the require.js config, eg.:

```js
var require ={
  wrap: true
};
```

(ag v3+ / ag-b 5+ required)

**Comment by rolandliwag** [comment]
Looks like this works. We just need to deal with a few issues with updating to the latest version of assetgraph-builder.
