### ISSUE TITLE
`node-zopfli` package seems no longer maintained

### ISSUE THREAD

**Issue by plroebuck** [assetgraph/assetgraph-builder#625]
[Seemingly abandoned](https://github.com/pierreinglebert/node-zopfli/issues/87) multiple months back. Binaries no longer available from AWS.

### Options
`bruce-one/node-zopfli` fork was reported to work.

This worked for me, but I _have_ build tools installed
```bash
$ npm install --build-from-source node-zopfli
```

**Comment by papandreou** [comment]
Hmm, depressing.

bruce-one's fork doesn't seem to be published as an npm package, and `npm i bruce-one/node-zopfli` fails on my Ubuntu box: https://gist.github.com/papandreou/6bf1fd441dc96c3062296fbb6a1b07e6

**Comment by papandreou** [comment]
We have the current node-zopfli as an optional dependency, so `npm install` should still succeed and we should handle it gracefully? https://github.com/assetgraph/assetgraph-builder/blob/04490bd8037ae1dc344b610df3125ed46e33d129/package.json#L65

**Comment by plroebuck** [comment]
As a user, I saw an error attempting installation. Yes, AG-B installed, but people unaware of the _optional_ nature would think the whole thing failed...

**Comment by salomvary** [comment]
👍 for removing this dependency. Even though it is an optional dependency, each time `npm install` is run it will try to install `node-zopfli` flooding the terminal with warnings and error messages.

**Comment by papandreou** [comment]
Already underway in https://github.com/assetgraph/assetgraph-builder/pull/633 🤗
