### ISSUE TITLE
Breaks relative ES6 module paths

### ISSUE THREAD

**Issue by salomvary** [assetgraph/assetgraph-builder#657]
Given

index.html
```
<script type="module">import main from './main.js'</script>
```

main.js
```
function main () {}
```

and the following command:
```
buildProduction --nocompress --outroot dist index.html
```

the resulting `dist/index.html` looks like this:
```
<script type=module>import main from'static/main.08791ac947.js'</script>
```

The problem: `static/main.08791ac947.js` is invalid as "bare" import specifiers aren't currently supported. It should be `./static/main.08791ac947.js`. [See also here](https://jakearchibald.com/2017/es-modules-in-browsers/).

Using assetgraph-builder@6.5.1.

**Comment by papandreou** [comment]
Thanks for the comprehensive report! Fixed in 6.6.1.

**Comment by papandreou** [comment]
Oh, make that 6.6.2 :)

**Comment by salomvary** [comment]
Awesome, thanks!

**Comment by papandreou** [comment]
Further fixes coming up in https://github.com/assetgraph/assetgraph/commit/97b394dd6930f102f3da7481abae26b4dc16c03e
