### ISSUE TITLE
[Q] CHANGELOG?

### ISSUE THREAD

**Issue by plroebuck** [assetgraph/assetgraph-builder#664]
Changes don't seem to be documented in GitHub releases.
Can't find CHANGELOG.

Where are changes documented?

**Comment by papandreou** [comment]
This is hitting a sore spot :)

Let's start with an autogenerated one:

* https://github.com/assetgraph/assetgraph-builder/blob/master/CHANGELOG.md
* https://github.com/assetgraph/assetgraph/blob/master/CHANGELOG.md

**Comment by plroebuck** [comment]
Thanks. There are large-ish gaps (e.g., 6.5.0->6.6.4, 6.6.4->6.9.0), but at least there's _some_ idea of what changed now...

**Comment by papandreou** [comment]
Yeah, I guess that's for changes that weren't done through PRs. Probably mostly upgrades of assetgraph.

We'll try to think of a better communication strategy for releases 😊

**Comment by papandreou** [comment]
We've been iterating on https://github.com/sunesimonsen/offline-github-changelog so those gaps don't appear, and I've now integrated it so the changelog gets regenerated on each release.
