### ISSUE TITLE
make assetgraph to not process svg

### ISSUE THREAD

**Issue by zba** [assetgraph/assetgraph-builder#687]
assetgraph breaks svg images with `<use>` is there any way to make it to not change svg files at all.

here is svg which broken:

`
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="145.4 334.5 18.1 18.1"><path id="a" fill="#70bf54" d="M145.7 345l2.6-6.7a13 13 0 0 1 1.3-2.7c.3-.5.8-.8 1.4-1 1.1-.3 1.8.1 2.1 1.2.2.9-.3 2.2-1.7 3.9l-4.9 6.3-.7.7c-.3 0-.4 0-.5-.3l.4-1.4z"/><use width="100%" height="100%" transform="rotate(19.3 138.3 355.9)" xlink:href="#a"/><use width="100%" height="100%" transform="rotate(41.3 140.4 356.1)" xlink:href="#a"/></svg>
`

it was converted to:

`
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="145.4 334.5 18.1 18.1"><path id="a" fill="#70bf54" d="M145.7 345l2.6-6.7a13 13 0 0 1 1.3-2.7c.3-.5.8-.8 1.4-1 1.1-.3 1.8.1 2.1 1.2.2.9-.3 2.2-1.7 3.9l-4.9 6.3-.7.7c-.3 0-.4 0-.5-.3l.4-1.4z"/><use width="100%" height="100%" transform="rotate(19.3 138.3 355.9)" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIxNDUuNCAzMzQuNSAxOC4xIDE4LjEiPjxwYXRoIGlkPSJhIiBmaWxsPSIjNzBiZjU0IiBkPSJNMTQ1LjcgMzQ1bDIuNi02LjdhMTMgMTMgMCAwIDEgMS4zLTIuN2MuMy0uNS44LS44IDEuNC0xIDEuMS0uMyAxLjguMSAyLjEgMS4yLjIuOS0uMyAyLjItMS43IDMuOWwtNC45IDYuMy0uNy43Yy0uMyAwLS40IDAtLjUtLjNsLjQtMS40eiIvPjx1c2Ugd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdHJhbnNmb3JtPSJyb3RhdGUoMTkuMyAxMzguMyAzNTUuOSkiIHhsaW5rOmhyZWY9IiNhIi8+PHVzZSB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiB0cmFuc2Zvcm09InJvdGF0ZSg0MS4zIDE0MC40IDM1Ni4xKSIgeGxpbms6aHJlZj0iI2EiLz48L3N2Zz4="/><use width="100%" height="100%" transform="rotate(41.3 140.4 356.1)" xlink:href="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20xmlns%3Axlink%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%22%20viewBox%3D%22145.4%20334.5%2018.1%2018.1%22%3E%3Cpath%20id%3D%22a%22%20fill%3D%22%2370bf54%22%20d%3D%22M145.7%20345l2.6-6.7a13%2013%200%200%201%201.3-2.7c.3-.5.8-.8%201.4-1%201.1-.3%201.8.1%202.1%201.2.2.9-.3%202.2-1.7%203.9l-4.9%206.3-.7.7c-.3%200-.4%200-.5-.3l.4-1.4z%22%2F%3E%3Cuse%20width%3D%22100%25%22%20height%3D%22100%25%22%20transform%3D%22rotate(19.3%20138.3%20355.9)%22%20xlink%3Ahref%3D%22data%3Aimage%2Fsvg%2Bxml%3Bbase64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIxNDUuNCAzMzQuNSAxOC4xIDE4LjEiPjxwYXRoIGlkPSJhIiBmaWxsPSIjNzBiZjU0IiBkPSJNMTQ1LjcgMzQ1bDIuNi02LjdhMTMgMTMgMCAwIDEgMS4zLTIuN2MuMy0uNS44LS44IDEuNC0xIDEuMS0uMyAxLjguMSAyLjEgMS4yLjIuOS0uMyAyLjItMS43IDMuOWwtNC45IDYuMy0uNy43Yy0uMyAwLS40IDAtLjUtLjNsLjQtMS40eiIvPjx1c2Ugd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdHJhbnNmb3JtPSJyb3RhdGUoMTkuMyAxMzguMyAzNTUuOSkiIHhsaW5rOmhyZWY9IiNhIi8%2BPHVzZSB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiB0cmFuc2Zvcm09InJvdGF0ZSg0MS4zIDE0MC40IDM1Ni4xKSIgeGxpbms6aHJlZj0iI2EiLz48L3N2Zz4%3D%22%2F%3E%3Cuse%20width%3D%22100%25%22%20height%3D%22100%25%22%20transform%3D%22rotate(41.3%20140.4%20356.1)%22%20xlink%3Ahref%3D%22%23a%22%2F%3E%3C%2Fsvg%3E"/></svg>
`

**Comment by papandreou** [comment]
Thanks for the report, I'll try to look into it tonight 🙏

**Comment by papandreou** [comment]
I think I fixed this in 6.10.2. If that doesn't work, could you let me know what your complete `buildProduction` command line is?
