### ISSUE TITLE
Getting undefined when creating a global function variable in a file loaded via require.js 

### ISSUE THREAD

**Issue by thbaja** [assetgraph/assetgraph-builder#69]
I'm using the sockjs-client module in a backbone+require.js setup.
(Sockjs-client on GH: https://github.com/sockjs/sockjs-client)

Source file: http://cdn.sockjs.org/sockjs-0.3.4.js

This part on line 30 seemed to be the problem:
```javascript
SockJS = (function(){
              var _document = document;
              var _window = window;
              var utils = {};
```
And avoiding being global by adding a 'var' in front helped:
```javascript
var SockJS = (function(){
```

**Comment by papandreou** [comment]
Hopefully this will be fixed with 5.0.0 now that we delegate to r.js for bundling.

Please reopen if that's not the case.
