### ISSUE TITLE
Requirejs: Use baseUrl from config file for the data-main attribute

### ISSUE THREAD

**Issue by thbaja** [assetgraph/assetgraph-builder#73]
Hello,

This is related to @papandreou's solution in this issue from where I copied some of the example: https://github.com/One-com/assetgraph-builder/issues/60

Having a folder structure like this:
js/config.js
js/main.js
index.html

And in requirejs config file having:
```javascript
var require = {
    baseUrl: './js'
};
```

Then it seems that the data-main attribute uses the baseUrl setting in require.js. So this will be the correct way to load the files:
```html
<script src="./js/config.js" charset="UTF-8"></script>
<script src="./js/vendor/require-2.1.5.js" charset="UTF-8" data-main="main"></script>
```

But this will not work with the builder, which still expect the path in data-main. So for assetgraph-builder, this will be correct:
```html
<script src="./js/config.js" charset="UTF-8"></script>
<script src="./js/vendor/require-2.1.5.js" charset="UTF-8" data-main="js/main"></script>
```

**Comment by papandreou** [comment]
This should work now that assetgraph/assetgraph#547 landed on master. Will be available in assetgraph-builder 5.x.
