### ISSUE TITLE
Developer friendly concatenation

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph-builder#75]
https://github.com/google/concatenate.js

Maybe we should have our `--nocompress` flag to do the same thing

**Comment by jackfranklin** [comment]
@Munter did you ever get anywhere with this? Looking ourselves at being able to deploy a sourcemap along with the main file; would mean we get much nicer errors in our prod environment.

**Comment by Munter** [comment]
I know assetgraph models source comments and source maps, but I don't think our bundling transforms adds sourceURL and I'm similarly unsure on the status of sourceMap support. The problem is I have used assetgraph mostly for non-build related stuff myself since I switched to companies that are unable to use it in their build process. Maybe @papandreou or @gustavnikolaj know more about sourceURL and sourceMap handling here

**Comment by jackfranklin** [comment]
Currently our set up of JS files that we ask AssetGraph builder to concat & minify are:

- traceur runtime
- SystemJS and config
- jspm generated bundle (not minified)

If there was a way of making sourcemaps survive through this process (jspm gives us sourcemaps) then that would be amazing. Currently our errors on prod are very hard to debug!

**Comment by Munter** [comment]
Adding `sourceURL` while bundling would have to happen somewhere around here (which it currently doesn't): https://github.com/assetgraph/assetgraph/blob/master/lib/transforms/bundleRelations.js#L101-L121

source maps would have to be added around here: https://github.com/assetgraph/assetgraph/blob/master/lib/transforms/compressJavaScript.js#L18-L37

**Comment by Munter** [comment]
`//#sourceURL=...` is only really relevant when no other manipulation of the assets has been done. Since we are offloading transpiling to third party tools more and more now I think this makes less sense, since there will be actual source maps to replace the functionality.

**Comment by papandreou** [comment]
Okay, thanks. Let's close this for now, then.
