### ISSUE TITLE
Generic requirejs plugin handling

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph-builder#90]
If we discover a requirejs dependency that uses a plugin type we do not support, or if the path to the dependency using the plugin cannot be resolved to a local path, we should add the requirejs plugin to the graph to keep functionality intact.

**Comment by papandreou** [comment]
All plugins should work now that https://github.com/assetgraph/assetgraph/pull/547 landed on master. Will be available in assetgraph-builder 5.x.
