### ISSUE TITLE
Require plugin 'text' not referenced correctly when used with an url

### ISSUE THREAD

**Issue by thbaja** [assetgraph/assetgraph-builder#91]
When defining a dependency with the 'text' plugin you would write something like this for an html template:
```javascript
'text!example.html'
```
But if you need to load a remote file like this, then there is a problem:
```javascript
'text!http://example.com/file.html'
```
It seems that the dependency is ignored because it contains an url, which means that the reference to the 'text'-plugin is kept as the original (development) path which doesn't exist in the final build.

**Comment by papandreou** [comment]
This should work now that assetgraph/assetgraph#547 landed on master. Will be available in assetgraph-builder 5.x.
