### ISSUE TITLE
Svgo is not a constructor

### ISSUE THREAD

**Issue by bramstein** [assetgraph/assetgraph-builder#990]
The latest release generates this error when optimizing SVG images:

```
TypeError: Svgo is not a constructor
```

It looks like the same issue as the optipng one, though I haven't looked into it closely.

**Comment by papandreou** [comment]
It's because it only works with svgo 1.x. They completely changed the api :weary:

I've backported an update to svgo 2.x and released assetgraph 7.8.0 and assetgraph-builder 9.2.0.

**Comment by bramstein** [comment]
Thanks for the quick turnaround! I appreciate it. :smiley:

**Comment by bramstein** [comment]
Could you also publish the npm package? Thanks!

**Comment by papandreou** [comment]
Urgh, sorry. Should be there now 😌
